### PR TITLE
fix(plugin): fail platform build when PagesJS build fails (fix #347)

### LINKED ISSUE #347: Platform build doesn't fail when PagesJS command fails
### Describe the bug

When a PagesJS command runs (ex 'pages build'), it does not return an exit code. This causes subsequent commands to run when PagesJS fails and creates confusing error logs.

Ex: in starting repo, running `npm run build` will call `yext pages build && yext pages generate-test-data && pages dev`. If there is an error in PagesJS build, it will continue to generate-test-data and error there.

### Reproduction

_No response_

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.66 GB / 32.00 GB
    Shell: 5.2.15 - /usr/local/bin/bash
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    pnpm: 8.4.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5
  npmPackages:
    @yext/pages: 1.0.0-beta.21 => 1.0.0-beta.21
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by jwartofsky-yext**
PagesJS commands now throw error codes properly. Subsequent commands no longer get executed on failure.

Example with an error added in closeBundle
errrorInCloseBundle

### CODE REVIEW

File: packages/pages/src/bin/spawn.ts [hunk 1]
```diff
@@ -13,10 +13,14 @@ const pathToPagesScript = path.resolve(
...
-spawnSync(
+const results = spawnSync(
   "node",
   ["--experimental-vm-modules", pathToPagesScript, ...process.argv.slice(2)],
   {
     stdio: "inherit",
   }
 );
+
+if (results?.status != undefined && results.status !== 0) {
```
Comment (mkilpatrick) [inline packages/pages/src/bin/spawn.ts:24]: Pretty sure you can just do results?.status !== 0

Comment (jwartofsky-yext) [reply packages/pages/src/bin/spawn.ts:24]: TypeScript doesn't seem to like that
image

Comment (mkilpatrick) [reply packages/pages/src/bin/spawn.ts:24]: Hmm ok

**Review by mkilpatrick — DISMISSED** [review]

**Review by mkilpatrick — APPROVED** [review]
