### PR TITLE
fix(dev): hydration does not reflect template data mutations

### LINKED ISSUE #298: mutations to template data are persisted between server and client renders
### Describe the bug

If template code mutates the template data passed into it during the initial generation of the page, those changes to the data are present during the initial client side render. 

For example, I'm using [this modification](https://github.com/yextconsulting/pages-starter-react-consulting/compare/mutation-report?expand=1) to our starter template, connected to account 3861963.

I would expect this code change to reverse the order of the contents of the `dm_directoryChildren` field. But what happens is that the field is reversed once during generation, then reversed again during the hydration pass. 

The result is that the server rendered content doesn't match the client rendered content which triggers a React error. 
image
In Firefox, the specific way the difference is reconciled leads to the text of the directory links not matching the hrefs, which is a particularly bad outcome. 

In general we should avoid this kind of mutation to props in our frontend code, but I also think this particular situation shouldn't be possible. 

### Reproduction

See description

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 21.74 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Firefox: 111.0.1
    Safari: 15.4
  npmPackages:
    @yext/pages: 1.0.0-beta.16 => 1.0.0-beta.16
```

### Used Package Manager

npm

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by benlife5**
fixes #298

### CODE REVIEW

File: packages/pages/src/dev/server/middleware/sendAppHTML.ts [hunk 1]
```diff
@@ -61,7 +63,7 @@ export default async function sendAppHTML(
 
   const clientInjectedServerHtml = getServerTemplateDev(
     clientHydrationString,
-    serverHtml,
+    await getServerHtml(),
```
Comment (mkilpatrick) [inline packages/pages/src/dev/server/middleware/sendAppHTML.ts:66]: This fixes the issue? Can you add a comment to the code about why we're doing this for future reference? Also, is there a way we could add a test for this?

**Review by mkilpatrick — COMMENTED** [review]
Can you remove the issue number from the PR title? It's linked in the description. We don't need it in both places.

File: packages/pages/src/dev/server/middleware/sendAppHTML.ts (hunk 1 above)
Comment (benlife5) [reply packages/pages/src/dev/server/middleware/sendAppHTML.ts:68]: Added comment. Honestly, I'm not entirely sure why this works, but it does. 

I started to look into testing it, I think it's doable but it takes a good bit of setup, possibly creating a test vite+express server. I think I have some higher priority items right now so I stopped but I'm happy to loop back to it if you want.

**Review by mkilpatrick — APPROVED** [review]
